export const FETCH_DIRECTORY = "FETCH_DIRECTORY";
export const PURGE_DIRECTORY = "PURGE_DIRECTORY";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const FETCH_DIRECTORY_SUCCESS = "FETCH_DIRECTORY_SUCCESS";
export const FETCH_DIRECTORY_ERROR = "FETCH_DIRECTORY_ERROR";

export const FETCH_COMPANY_CONTACTS = "FETCH_COMPANY_CONTACTS";
export const FETCH_COMPANY_CONTACTS_SUCCESS = "FETCH_COMPANY_CONTACTS_SUCCESS";
export const FETCH_COMPANY_CONTACTS_ERROR = "FETCH_COMPANY_CONTACTS_ERROR";

export const FETCH_PERSONAL_CONTACTS = "FETCH_PERSONAL_CONTACTS";
export const FETCH_PERSONAL_CONTACTS_SUCCESS =
  "FETCH_PERSONAL_CONTACTS_SUCCESS";
export const FETCH_PERSONAL_CONTACTS_ERROR = "FETCH_PERSONAL_CONTACTS_ERROR";

export const FETCH_GROUPS = "FETCH_GROUPS";
export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_ERROR = "FETCH_GROUPS_ERROR";

export const FETCH_PHONE_CONTACTS = "FETCH_PHONE_CONTACTS";
export const FETCH_PHONE_CONTACTS_SUCCESS = "FETCH_PHONE_CONTACTS_SUCCESS";
export const FETCH_PHONE_CONTACTS_ERROR = "FETCH_PHONE_CONTACTS_ERROR";

export const UPDATE_COMPANY_CONTACT = "UPDATE_COMPANY_CONTACT";
