export const APP_FOREGROUND = "APP_FOREGROUND";

// Notification Actions
export const STORE_PUSH_TOKEN = "STORE_PUSH_TOKEN";
export const CLEAR_PUSH_TOKENS = "CLEAR_PUSH_TOKENS";
export const UPDATE_NOTIFICATION_PERMISSIONS =
  "UPDATE_NOTIFICATION_PERMISSIONS";
