export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOG_OUT = "LOG_OUT";
export const SET_MFA_SETUP_STATE = "SET_MFA_SETUP_STATE";
export const CLEAR_MFA_SETUP_STATE = "CLEAR_MFA_SETUP_STATE";
